### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by rudyv** [evilgeniuslabs/tree#1]
Hi Jason,

Beautiful project, I tried to compile it and it doesn't work.
This is what I did:
I copied tree.ino and all related .ccp and .h files into the build IDE from Particle. Unfortunately it doesn't compile.
I get compiler errors:

"""""""""""""""""""""""
In file included from pixeltypes.h:5:0,
                 from power_mgt.h:4,
                 from tree.cpp:5:
lib8tion.h:2:2: error: #error WTH? led_sysdefs needs to be included first
 #error WTH?  led_sysdefs needs to be included first
  ^

In file included from tree.cpp:11:0:
lib8tion.h:2:2: error: #error WTH? led_sysdefs needs to be included first
 #error WTH?  led_sysdefs needs to be included first
"""""""""""""""""""""""

Can you help me out with this ?
How did you get it to compile ?

KR,
Rudy

**Comment by jasoncoon** [comment]
Thanks!

I haven't tried it in the Particle Build IDE, but it should work if you delete the FastLED directory, and include the FastLED library: https://docs.particle.io/guide/getting-started/build/photon/#using-libraries

I use Particle Dev, and it should work fine, let me know if it doesn't: https://www.particle.io/dev

**Comment by rudyv** [comment]
Thanks for the feedback Jason, 

I'm downloading the dev environment right now, this project and the holiday season justify it :) 
I'll keep you informed. 
KR, 
Rudy 

----- Original Message -----

**Comment by rudyv** [comment]
Hi Jason,

it compiles in dev, fantastic. The only thing is now that I have G and R swapped and even when I try to change that with giving GRB as an input to FastLED.addLeds<WS2812B, TX, GRB>(leds,NUM_LEDS);
Any suggestion on that ?
KR,
Rudy

**Comment by rudyv** [comment]
Jason, I figured it out, it works, great :)
